= Coding Guidelines
Nidhi Anand <nidhi.anand@centricconsulting.com> v1.0, 06-19-2022

Why Coding Guidelines?

The coding guidelines are important because most of the software cost goes towards maintenance.
Therefore, maintaining a convention for writing software increases the readability of the program.

*1. Naming Conventions*
Camel case convention should be followed in java programming. It means that all the classes and interfaces should be nouns, in mixed cases with the first letter of each internal word capitalized. All the methods should be verbs, in mixed case with the first letter lowercase and with the first letter of each internal word capitalized. The variables should be meaningful and one character variable names must be avoided. A constant variable is defined in the capital case.

*2.Curly Braces*
Curly braces are used to define the bodies of classes, methods, and loops. There are two standard formats for the usage of curly braces, either of which is used.

 * No blank lines should be present after the opening brace or before the closing brace.
 * A curly brace is applied at the end of the line that starts the class, method, loop, etc., and the closing brace is on a line by itself, lined up vertically with the start of the first line.
---------------
  For example:
  class Test {
       Test (){
    // Constructor

    }
    int Test(int a, float b){

        for (int i = 0; i < Field; i++){

        }
    }
  }
---------------
  * Each curly brace is added on a new line, and the pair is aligned vertically. The preceding code snippet in this format would be as follows:
---------------
   class Test
   {
     ... Test()
     { // Constructor

     }
      int Test(int a, float b)
     {
        for (int i = 0; i < Field; i++)
       {

       };
     }
   }
---------------

*3.Indentation*
 The unit of indentation should be 4 spaces. Tab-stops should be set exactly every 8 spaces. All indentation must be achieved by the space character and tab characters must not exist in the resultant source file. The recognized standard for increasing readability of each line is:

 * Apply indentation to alike items in a vertical list (such as end-of-line comments, and identifiers in declarations).
 * Surround the binary operators (including assignment) by spaces.
 * Follow a semicolon or comma by a space.
 * Add a space between a keyword(“if”, “while”, “return”, “catch”, “switch”, “for”) and a succeeding parenthesis.
 * Surplus parentheses can also help to highlight the structure of expressions (but avoid using too many nested parentheses).
 * Insert blank lines to differentiate between the important parts of the code.
 Let’s implement all the above guidelines in a code:
 ---------------
 class Test{
    private int s;
    private double d;

    Test()
    {  // Constructor
        s = 1;
        d = 3.14;
    }

    int Test(int a, float b)
    {
        // Must initialize local variables
        int l = 0;
        float le = 1;
        int n = 10;
        l = n - 2;
        le = l + b * 3;

        for (int i = 0; i < n; i++) {
                   l = l * 2;
                   l = l - n;
         }
               return l + a;
      }
    }
 ---------------

*4.White Space*
 White spaces also play a major part in readability as follows:

  * Operators should be surrounded by a space character. For example:
   The operation should be written as:

   a = (b + c) * d;
   And not as:
   a=(b+c)*d


 * Reserved words of Java should be followed by white space. For example:
  The loop must be initialized as:

  while (true) {…}
  And not as:
  while(true){…}

 * Commas should be followed by white space. For example:
  The functions must be initialized as:

   fun(a, b, c, d);
   And not as:
   fun(a, b, c, d);

 * Semicolons in for statements should be followed by a space character. For example:
  The for loop must be initialized as:

  for (i = 0; i < n; i++)
  And not as:
  for(i=0;i<n;i++)


*5.Comments*
   Comments should contain only the information that is relevant for reading and understanding the program.
   For example, information about how the package is built or in what directory it resides should not be included in the program as a comment.
   Java programs can have two types of comments.

   * Implementation Comments: Implementation comments are delimited by //. Java also allows the use of /*…*/ for implementation comments. Implementation comments are used for notes about a particular implementation or for temporarily removing code.
    Programs can have four styles of implementation comments: block, single-line, trailing, and temporarily removing code.

   * Block comments are used to provide descriptions of files, methods, data structures, and algorithms. Block comments may be used at the beginning of each file and before each method or within methods.
     Block comments inside a method should be indented to the same level as the code they describe. A block comment should have a blank line before its start unless it comes immediately after the start of a compound statement.
     For example:
    // block comment on line 1
    // block comment on line 2
    // block comment on line 3

   * Single-line comments can appear on a single line indented to the level of the code that follows. If a comment can not be written in a single line, it should follow the block comment format.
     A single-line comment should be preceded by a blank line unless it comes immediately after the start of a compound statement.

    For example:
    a = 10;
    b = 20;
    // a single-line comment
    c = a * b;


   * Trailing(very short) comments can appear on the same line of the code they describe but should be separated from the code at a far off distance.
      If more than one short comment appears in a section of related code, they should all be indented to the same tab setting.

      For example:
       if (a == 2) {
       b = true; // special case
      }
      else {
        c = isPrime(x); // works only for odd
      }

    * Temporarily removing code: The // delimiter can comment out a partial or a complete line. It can also be used in multiple lines to comment out entire sections of code.
       It is important to note that this should only be used temporarily while the code is in active development; the unused code should eventually be physically removed as it can make the source more difficult to maintain.

       For example:
        if (a > 1) {
        b = a; // + 1;
        ...
       }
       else {
       // b = 2;
       ...
       }

     * Documentation Comments: Documentation comments describe Java classes, interfaces, constructors, methods, and fields. They are delimited by /**…*/. Note the double-asterisk (**) at the beginning with one comment per class, interface, or member.
       This comment should appear just before the declaration with no space between the comment and the code it refers to. Documentation comments can be extracted to HTML files using the javadoc tool.

       Javadoc of class members can be specified on a single line as follows:
      /** This is a java documentation comment */
      private int comments_;


*6. Hardcoding*
    Hardcoding values in code can often lead to multiple side effects. For instance, it can lead to duplication, which makes change more difficult. It can often lead to undesirable behavior if the values need to be dynamic.
    In most of the cases, hardcoded values can be refactored in one of the following ways:

    * Consider replacing with constants or enums defined within Java
    * Or else, replace with constants defined at the class level or in a separate class file
    * If possible, replace with values which can be picked from configuration or environment

      Let's see an example:
      private int storeClosureDay = 7;
      // This can be refactored to use a constant from Java
      private int storeClosureDay = DayOfWeek.SUNDAY.getValue()



















.